# Generated by Django 4.2.2 on 2023-07-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_lvl', models.BooleanField()),
                ('faculty', models.CharField(max_length=64)),
                ('profile', models.CharField(max_length=64)),
                ('edu_form', models.CharField(max_length=64)),
                ('course', models.IntegerField()),
                ('stream', models.IntegerField()),
                ('group', models.IntegerField()),
                ('group_code', models.CharField(default='<django.db.models.fields.BooleanField>.<django.db.models.fields.CharField>.<django.db.models.fields.CharField>.<django.db.models.fields.CharField>.<django.db.models.fields.IntegerField>.<django.db.models.fields.IntegerField>.<django.db.models.fields.IntegerField>', max_length=256)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
