# Generated by Django 4.2.2 on 2023-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(max_length=256),
        ),
    ]
